### ISSUE TITLE
[bug] Mime type of docs is not right

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/cozy-desktop#123] opened 2015-11-03 09:51 UTC
It seems by default, the mime type of files is image/jpeg.

**Comment by nono** [comment] 2015-11-03 10:00
@ZeHiro currently, cozy-desktop has only a read-only mode, ie it copies the files and folders from a remote cozy to a local hard drive. The mime-type in pouchdb is taken from the remote couchdb. Can you look in your couchdb to see if the files have an `image/jpeg` mime-type?

**Comment by ZeHiro** [comment] 2015-11-03 10:06
@nono, in fact it seems I had sync problem. As all the files with mimetype image/jpeg are all 803 kb size. And I get 
```
error - Pouch/CouchDB  | An error occured during replication.
error - Pouch/CouchDB  | {}
```

**Comment by nono** [comment] 2015-11-03 10:09
@ZeHiro how did you install cozy-desktop: npm or git? Does these files come from the android app?

**Comment by ZeHiro** [comment] 2015-11-03 10:19
I installed with npm. should I install it with git?
And they wer imported with Firefox/Files app, Android app and konnectors.
No difference.

**Comment by nono** [comment] 2015-11-03 10:22
The version on npm is still the 0.3.0, from before I start working on it. So, if you want to test my code, yes, you should install it with git (or wait that we publish a version on npm - soon).

**Comment by nono** [comment] 2015-11-03 11:39
I close this issue as a duplicate of https://github.com/cozy-labs/cozy-desktop/issues/86. Feels free to reopen it / open other issues.

**Closed by nono** 2015-11-03 11:39 UTC
