### ISSUE TITLE
Ubuntu 18.04 : Crash and desktop freeze

### ISSUE THREAD

**Issue by zedalaye** [cozy-labs/cozy-desktop#1055] opened 2018-05-26 15:48 UTC
### Description

When I start Cozy Desktop app on my Ubuntu 18.04 box everything freezes and I have to hard reboot.

### Steps to Reproduce

1. Download .AppImage
2. Start .AppImage

### Expected behavior

Cozy Desktop show up and start syncing my files

### Actual behavior

Its like the UI was beeing built (I saw something like a window shadow) then everything is frozen.

### Informations

* **reproductible**: always
* **OS**: linux
* **version**: 3.6.0

**Comment by sebn** [comment] 2018-06-06 07:13
Thank you for reporting the issue!

We'll need more information to investigate this one.
There should be some logs in `~/.cozy-desktop/`, we need at least the most recent one : `logs.txt`.
Please note logs include your filenames.

You can eventually install [bunyan](https://github.com/trentm/node-bunyan) (needs [Node.js](https://nodejs.org/)) and run `bunyan -o short -l error ~/.cozy-desktop/logs.txt` to find out eventual error details.

In case that sounds a bit complicated, or you don't really have time to deal with this, you can also just upload the `logs.txt` file to https://send.firefox.com/ and share the download link with us *through some private channel* (Cozy contact email mentioning this issue, or IRC private message to me).

The app usually allows sending a support request directly from the UI (which automatically includes logs), but this won't help in your case since it crashes before even showing up.

Please tell me in case you need help for any of those steps.

**Comment by bristow** [comment] 2018-06-25 16:55
Same thing on my computer on Ubuntu 18.04 (laptop Lenovo X240). After sync, it's ok but laptop isn't useable during syncing.

Do you still need a log ?

**Comment by bristow** [comment] 2018-06-27 09:08
I send you my last log.txt (only 24h), i haden't wifi active but my laptop was unuseable at startup.

https://framadrop.org/r/uKFMJE4Bzc#zSkW8wukdd0rqdKJ+RmKFxfimKLpQCIKIeEGEH0Qpr4=

**Comment by bristow** [comment] 2018-07-08 11:17
@sebn some news ? I'd like to change my hubiC for cozy but i need a client for my professional laptop on Ubuntu 18.04.
Thanks !

**Comment by sebn** [comment] 2018-07-14 08:08
@bristow Sorry, we're quite overwhelmed.

The app logs don't show any issue at all. We'll probably need to take a look at the kernel logs in this case, but their location/availability may vary from one distro to another, and I'm not sure where they are located on latest Ubuntu LTS (possibly `/var/log/kern.log`?). I'll try to take a look at it as soon as possible.

**Comment by bristow** [comment] 2018-07-14 08:33
@sebn : I don't understand...

I restart today and everything works fine, i made an update before...

@zedalaye could you test again ?

**Comment by bristow** [comment] 2018-07-18 11:01
@sebn forgot what i said... Same problem again...

You can find my kern.log here : https://framadrop.org/r/ts_cf6fT2w#LrqdM2W6IRwRKv5VwHCXFmrVpwyK42fePwFE/Aclu9E=

I made 2 reboots today, 18th july.

**Comment by sebn** [comment] 2018-07-19 12:58
> Same thing on my computer on Ubuntu 18.04 (laptop Lenovo X240). After sync, it's ok but laptop isn't useable during syncing.

Sorry, I misread, my bad.

The ressource consumption issue is known and not the same as the desktop crashing one.
For the former, we just need more app logs, ideally all the `logs.txt*` files.
Please note we're already investigating quite a few support requests, so it make take some time.

**Comment by bristow** [comment] 2018-07-19 13:46
You can find logs.txt here : https://framadrop.org/r/48Yt6j4SYR#Zke940LA6MOIsbL9TsI37vDh4kE75FbtsmC9s6FVeCI=

250 MB for logs is too big, don't you think ?

**Comment by sebn** [comment] 2018-07-19 15:38
> you can find logs.txt here

Thanks!

> 250 MB for logs is too big, don't you think ?

Definitely, it may even get bigger... That's another known issue.

**Comment by Wenzel** [comment] 2018-08-12 22:57
It looks like the problem is coming from `Ubuntu`'s Gnome extension to get a system tray for legacy icons.

I remove the package responsible for this:
`sudo apt purge gnome-shell-extension-appindicator`
And `CozyDrive` doesn't crash anymore or freezes the desktop !

Althought, the window cannot be displayed.

Switching to the `Mate` desktop is the solution..

**Comment by sebn** [comment] 2018-08-17 06:59
Hello there, we'll be using Ubuntu 18.04 and testing it more extensively soon (including fixing the auto-launch that seems to break after an upgrade), we'll get back to you as soon as possible. We apologize for the delay.

**Comment by bristow** [comment] 2018-08-18 10:27
Thanks @Wenzel for your research  and @sebn for your work !

**Comment by bristow** [comment] 2018-09-12 20:41
Some news @sebn for this bug ?

**Comment by sebn** [comment] 2018-09-21 21:50
Sorry for the late answer.
I have no idea whether my teammate encountered the issue while testing on 18.04.
I hope to be able to upgrade one of our dependencies (electron) soon, which should hopefully fix this issue (and many other small ones). I'll give Ubuntu LTS a try myself while upgrading.

**Comment by Wenzel** [comment] 2018-10-25 12:35
Hi,
I just gave another try to your app this afternoon.
1 minute after i started it, my Mate desktop was frozen.
I can't say for sure that it comes from the app of course, but the coincidence raises some suspicions here... :thinking: 

After the reboot, i ran the app again, this time it doesn't crash the desktop but it remains unresponsive for a few minutes, and then it works as expected.

It think something is really wrong when you can crash the user's desktop.
This ticket should have a higher priority as it's not a simple bug in the app. :neutral_face:

version: `3.10.0`

**Comment by nono** [comment] 2018-10-25 13:12
Hello @Wenzel,

can you send us a message from the application? It will send us the logs, and it will be really helpful to understand what it happened.

**Comment by Wenzel** [comment] 2018-10-25 13:15
@nono i have already been syncing thousands of files now that the app is running.

Should i still send you a report via the app ?

**Comment by nono** [comment] 2018-10-25 13:19
@Wenzel yes, we should still look if we see anything obviously wrong that may have provoked the OS crash.

**Comment by Wenzel** [comment] 2018-10-25 22:44
I tried to reproduce the bug in a fresh Ubuntu `18.04 LTS` VM, and so i managed to complettely crash the desktop.
I suspect that the system ran out of memory.
Sometimes the app is eating `1GB+` of RAM for no reason.

I recorded a video of one of my attempts, the app becomes unresponsive for a few minutes after initialization, and eats a lot of RAM:
https://drive.google.com/open?id=1n0108XX6jn4Br3zPbW7kO0SCAs0hgk2y

I hope that helps !

**Comment by Wenzel** [comment] 2018-10-26 07:32
@nono yes, i already have thousands a files (`21 000`) uploaded on my Cozy.
That's why the app is maybe having a hard time to make the initial sync.
But it should remain responsive :)

**Comment by nono** [comment] 2018-10-26 07:55
@Wenzel my question was not about the files on the Cozy, but on the hard disk. If your local folder is clean when you start, the good news is that we are working to improve the initial Cozy to hard disk synchronization. But we also some performance issues for files on the local disk, and it will take more time to fix those issues.

**Comment by Wenzel** [comment] 2018-10-26 08:07
@nono ah yes, the local folder `Cozy Drive` was empty and created by `Cozy Desktop`.

**Comment by bristow** [comment] 2018-10-31 11:06
@sebn @nono 
Some news about this big big bug ? All my colleagues are impacted and it's very complicated.

Do you need more informations ?

**Comment by Wenzel** [comment] 2018-10-31 11:09
@bristow can you watch the RAM usage when you launch the app ?

Are you running the default Ubuntu desktop ?

Does it crashes and restart or does it freezes ?

**Comment by bristow** [comment] 2018-10-31 13:43
It freezes...

I run default Ubuntu desktop with Gnome-Shell.

You can see my RAM et SWAP after few minutes : 
![htop](https://framapiaf.org/system/media_attachments/files/001/618/968/original/1e14c8a890d4a53c.png?1540990953)

**Comment by Wenzel** [comment] 2018-10-31 13:46
`gnome-shell` is using `88,6`% of the RAM :thinking: 
Not the Cozy Desktp app as I first thought.

Maybe the app is triggering a memory leak in `Gnome-Shell` ?
@sebn @nono is there a way could you get in touch with Gnome developers ?

**Comment by Wenzel** [comment] 2018-10-31 13:57
@bristow are you running Ubuntu 18.04 ?

The new release 18.10 is shipped with Gnome 3.30, and IIRC they fixed some memory leaks:
https://linuxfr.org/news/parution-de-gnome-3-30#toc-un-coup-de-boost

Maybe you can try to upgrade and give us a feedback ?

**Comment by bristow** [comment] 2018-10-31 14:33
It's difficult for me because this is my professional laptop and i prefer to stay in LTS release...

**Comment by bristow** [comment] 2019-01-10 14:39
A little up for 2019 :+1:

**Comment by whiver** [comment] 2019-01-28 11:55
I installed Cozy Desktop yesterday and same issue for me under Ubuntu 18.10 with gnome desktop. It freezes regularly for around 1 min while syncing, with a quite high CPU usage (~20% after the freeze, which is still quite high for a i5 CPU) and high disk usage too.
Note that it happens even if my files didn't change.

I did not install the gnome extension to get the notification icon, but I followed [this thread](https://askubuntu.com/a/1056242/836889) instead.

**Comment by whiver** [comment] 2019-01-29 21:03
Update: the freeze also appears each time I copy several files to the Cozy Drive folder: I copy-paste the folder, and immediately the desktop freezes, before the copy completes. Then after some time (~5 min), the window manager crashes. By switching to another tty, running htop shows that 100% of the CPU is used by `apport`. (cozy is using ~10% CPU and ~100Mo of RAM).

**Comment by nono** [comment] 2019-02-04 15:58
@bristow we had several reports that gnome-shell is very unstable. There are a lot of memory leaks and crash reports on https://bugzilla.gnome.org/. Maybe you can open an issue on https://gitlab.gnome.org/GNOME/gnome-shell/issues.

@whiver `apport` is a tool by Ubuntu for reporting crash of applications to their developers. I think that the real culprit is gnome-shell and it has crashed just before you switch to the other tty.

And, for the record, I've tried to reproduce the issue on a fresh install of Ubuntu 18.04, but it works fine with some thousands files. From the bug reports of gnome-shell, I think it depends of the graphic cards and I'm lucky.

**Comment by whiver** [comment] 2019-02-04 20:25
The reason why I mentioned `apport` is about its CPU use, precisely because being a report tool, it shouldn't take so much resources.

My Ubuntu install is almost fresh too: Ubuntu 18.10, and I installed [`libappindicator-dev`](https://askubuntu.com/questions/1056226/ubuntu-budgie-18-04-lts-system-tray-icons-not-all-showing/1056242#1056242) to get the notification icon working for Cozy.
Is there something I can do to help you get some telemetry or logs? The freeze repro each time I start Cozy.

**Comment by bristow** [comment] 2019-02-04 20:35
@nono i'm not agree with you. Gnome Shell works very well, i have only one problem, this is with Cozy :(

I can also help but get some logs is very difficult because we need to restart computer...

Thanks :+1:

**Comment by nono** [comment] 2019-02-05 07:55
@whiver can you try to remove libappindicator-dev and use [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) instead?

@bristow maybe you can try to reproduce the freeze/crash with another window manager. At least, we would know if it is really a gnome-shell bug (probably not in the gnome-shell codebase, maybe an extension, or my favorite guess, a bad combination with a graphic card driver).

**Comment by whiver** [comment] 2019-02-12 21:18
@nono I tried to use Topicons Plus and after a few days of use I didn't notice any freeze, so I guess the problem is solved. Thanks for your help! :)
Though this is quite odd that the native solution is causing freezes whereas the extension solution works.

**Comment by bristow** [comment] 2019-02-13 15:00
Sorry @whiver but i am not so optimistic.

Indeed, i installed Top icons on my Ubuntu 18.04 up to date, and i have big freeze when i launch Cozy. I have the mouse' s pointer but i can't click, no effect. I had to halt my laptop with a long press on power button.

**Comment by gpronost** [comment] 2019-02-19 01:18
Hi, actually I have the same troubles than @bristow, except that I don't need to halt my laptop. It recovers from the freeze after several minutes (usually 5).
It seems however, that gnome itself (or the x server) crashes, as the recovering always occur with a "refresh" of gnome (black screen and gnome's items reappearing one by one).

**Comment by Wenzel** [comment] 2019-02-19 10:42
We should include Gnome developers here and get their opinion about this, as it seems related to Gnome desktop only.

Does anyone know a Gnome dev who could give some help ?

**Comment by nono** [comment] 2019-02-19 11:13
@Wenzel it is a good idea. Currently, our efforts are mostly on the local watcher (the integration with inotify and ReadDirectoryChangesW) that will improve cozy-desktop for a lot of people, and this issue is not on our priority list as we have few users on Ubuntu with gnome. If a gnome developer can help us, it would be a good way to advance on this topic. I don't know a gnome developer, but maybe someone else on this thread does.

**Comment by gpronost** [comment] 2019-02-20 07:03
I tried to upgrade to 18.10 in order to see if it could solve the issue. So far, it doesn't. However, I got a trace in the syslog. Maybe it can help:

Feb 20 15:40:46 neutrino gnome-shell[2735]: message repeated 2 times: [ [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_4575]
Feb 20 15:40:46 neutrino gnome-shell[2735]: [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_4578
Feb 20 15:41:32 neutrino gnome-shell[2735]: message repeated 3611 times: [ [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_4578]
Feb 20 15:41:32 neutrino gnome-shell[2735]: ../../../../glib/gmem.c:135: failed to allocate 32 bytes
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: GNOME Shell crashed with signal 5
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: == Stack trace for context 0x55b19a6e3210 ==
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #0   7fff92c183f0 I   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:309 (7f6f5b632550 @ 680)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #1   7fff92c184d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f6f63cb0b80 @ 71)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #2   7fff92c18540 I   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:260 (7f6f5b6324c0 @ 115)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #3   7fff92c18620 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f6f63cb0b80 @ 71)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #4   7fff92c186c0 I   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:425 (7f6f5b632820 @ 960)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #5   7fff92c18790 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f6f63cb0b80 @ 71)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #6   7fff92c18800 I   self-hosted:977 (7f6f63cf0280 @ 413)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #7   7fff92c18870 I   self-hosted:977 (7f6f63cf0280 @ 413)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #8   7fff92c188f0 I   resource:///org/gnome/gjs/modules/signals.js:128 (7f6f63cc18b0 @ 386)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #9   7fff92c18940 I   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:162 (7f6f5b6320d0 @ 96)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #10   7fff92c189d0 I   self-hosted:261 (7f6f63cc1dc0 @ 223)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #11   7fff92c189d0 I   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:156 (7f6f5b632040 @ 65)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #12   7fff92c18ab0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f6f63cb0b80 @ 71)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #13   7fff92c18b30 I   self-hosted:981 (7f6f63cf0280 @ 474)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #14   7fff92c18bb0 I   self-hosted:981 (7f6f63cf0280 @ 474)
Feb 20 15:41:32 neutrino org.gnome.Shell.desktop[2735]: #15   7fff92c19ca0 b   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:42 (7f6f5b63b670 @ 145)

**Comment by bristow** [comment] 2019-02-20 08:46
Good Job @gpronost 

I found the same thing on my old syslog : 

`Feb  5 12:53:13 ThinkPad-X240 gnome-shell[5196]: [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_1997
Feb  5 12:54:59 ThinkPad-X240 gnome-shell[5196]: message repeated 331 times: [ [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_1997]
`

**Comment by Wenzel** [comment] 2019-02-20 08:47
@nono I propose that you send an email to the `desktop-devel-list@gnome.org` mailing list, asking Gnome developers for advices regarding this issue.

I guess if it's someone representing CozyCloud, you would get more attention.

**Comment by bristow** [comment] 2019-02-21 09:47
I have opened an issue here : https://gitlab.gnome.org/GNOME/gnome-shell/issues/984

**Comment by bristow** [comment] 2019-02-21 14:49
I think Didier Roche, Canonical developper, has made good progress on this problem : [](https://gitlab.gnome.org/GNOME/gnome-shell/issues/984#note_442716)

> I think there are 3 bugs :

> 1 - CozyCloud is referencing an asset that doesn't exist, this is what caused the other improper behavior
> 2 - ubuntu-appindicators shouldn't try to load and reload in loop the invalid asset. This is filed as bug https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1817073 and tracked for release
> 3- GNOME Shell should be more resilient and don't crash when too many logs are repeatidly written.

> The CozyCloud extension is what caused the 2 other components to misbehaved. We'll protect appindicators against it, but the 2 other bugs will remain.

**Comment by Wenzel** [comment] 2019-02-21 16:36
So, IIRC, you could temporarily fix the bug by fixing the asset reference ?

**Comment by nono** [comment] 2019-02-21 17:23
If we have a missing asset reference and we found which one, we will fix the missing asset reference. But, for the moment, I don't see any missing asset reference. From the timing, I think it should be this asset: https://github.com/cozy-labs/cozy-desktop/blob/master/gui/images/tray-icon-linux/sync.png but I've checked, this file is included in our releases. I've tried some other things, but I haven't found yet what we are doing wrong.

**Comment by gpronost** [comment] 2019-02-22 03:06
I'm not sure this is the asset AppIndicator is looking for. Looking at the code of AppIndicator, it send this message here:

            icon_info = icon_theme.lookup_icon(icon_name, icon_size,
                                               Gtk.IconLookupFlags.GENERIC_FALLBACK)

            // no icon? that's bad!
            if (icon_info === null) {
                Util.Logger.fatal("unable to lookup icon for "+icon_name);
            } else { // we have an icon
             `

The icon_name, according to the debug is "Cozy Drive1_XXXX" (with XXXX a number). Maybe there is an issue in the declaration of the icon name? I'm not familiar enough with electron and GNOME so maybe I'm saying _non-sens_, but if we can find where this "Cozy Drive1" is coming from, maybe we could understand what the issue is?

**Comment by gpronost** [comment] 2019-02-22 03:20
Looking at the dbus monitoring I have the following:

        method call time=1550804988.791673 sender=:1.21 -> destination=:1.71 serial=55755 path=/org/ayatana/NotificationItem/Cozy_Drive1; interface=org.freedesktop.DBus.Properties; member=Get
                string "org.kde.StatusNotifierItem"
                string "IconPixmap"
        error time=1550804988.791837 sender=:1.71 -> destination=:1.21 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=55755
                string "No such property “IconPixmap”"
        method call time=1550804988.791947 sender=:1.21 -> destination=:1.71 serial=55756 path=/org/ayatana/NotificationItem/Cozy_Drive1; interface=org.freedesktop.DBus.Properties; member=Get
                string "org.kde.StatusNotifierItem"
                string "IconName"
        method return time=1550804988.792106 sender=:1.71 -> destination=:1.21 serial=91145 reply_serial=55756
                variant       string "Cozy Drive1_18224"
        method call time=1550804988.792256 sender=:1.21 -> destination=:1.71 serial=55757 path=/org/ayatana/NotificationItem/Cozy_Drive1; interface=org.freedesktop.DBus.Properties; member=Get
                string "org.kde.StatusNotifierItem"
                string "IconThemePath"
        method return time=1550804988.792465 sender=:1.71 -> destination=:1.21 serial=91146 reply_serial=55757
                variant       string "/tmp/.org.chromium.Chromium.wuM470"
        method call time=1550804988.792705 sender=:1.21 -> destination=:1.71 serial=55758 path=/org/ayatana/NotificationItem/Cozy_Drive1; interface=org.freedesktop.DBus.Properties; member=Get
                string "org.kde.StatusNotifierItem"
                string "IconPixmap"
        error time=1550804988.792827 sender=:1.71 -> destination=:1.21 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=55758
                string "No such property “IconPixmap”"
        method call time=1550804988.792836 sender=:1.21 -> destination=:1.71 serial=55759 path=/org/ayatana/NotificationItem/Cozy_Drive1; interface=org.freedesktop.DBus.Properties; member=Get
                string "org.kde.StatusNotifierItem"
                string "IconName"
        method return time=1550804988.792951 sender=:1.71 -> destination=:1.21 serial=91148 reply_serial=55759
                variant       string "Cozy Drive1_18224"

If I understand correctly, something ask for the IconName for Cozy Drive here, and the reply is "Cozy Drive1_18224". I quite don't understand why the reply to IconThemePath is something linked to chromium however. 

Note that here Gnome was not freezing, and at the same time I got the following in the syslog:

        Feb 22 12:10:49 neutrino gnome-shell[2784]: [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_18224
        Feb 22 12:10:49 neutrino gnome-shell[2784]: [AppIndicatorSupport-FATAL] unable to lookup icon for Cozy Drive1_18224

**Comment by nono** [comment] 2019-02-22 10:03
> If I understand correctly, something ask for the IconName for Cozy Drive here, and the reply is "Cozy Drive1_18224".

I'd say so. 18224 is probably the PID (process identifier). And I think it is AppImage that sets the name to `Cozy Drive 1_XXX`.

> I quite don't understand why the reply to IconThemePath is something linked to chromium however (chromium is my browser).

I don't think it is linked to your browser: Electron embeds a chromium in the application.

**Comment by gpronost** [comment] 2019-03-05 02:34
Did someone test if the work-around solve the issue? (I can't test it)

**Comment by bristow** [comment] 2019-03-05 14:37
@nono how can we test this work-around ? Is there a new AppImage ?

**Comment by Wenzel** [comment] 2019-03-05 14:44
@bristow  There are development artifacts available on each pull request apparenly:
https://github.com/cozy-labs/cozy-desktop/pull/1463#issuecomment-466347453

**Comment by manuch54** [comment] 2019-04-07 16:44
Just to share my personal experience, and perhaps help to solve this issue, here is what leaded me to stop having Gnome frozen at startup.

First, I was wondering if it was a question of Gnome version. I was on Ubuntu 18.04 and I upgraded to 18.10 and 19.04 on which I'm now. None of those upgrades solved the issue. Then I read once again the installation guidelines from Cozy's website where it is mentioned that we need to install TopIcons extension to see the icon on the top bar. As far as this extension doesn't work on Ubuntu Disco Dingo, I simply removed it. Until then, I was using TopIcons Plus extension which works on all versions and creates this startup freeze. Now that I have no TopIcons extension, there is no freeze.

Finally, the problem is here : TopIcons extensions create the freeze. So there might be something to seek in there.

Hope this helps...

**Comment by gpronost** [comment] 2019-04-29 10:15
Hi guys, just to confirm that the issue seems to be fixed with the last release :)

**Comment by B-Galati** [comment] 2019-05-01 12:41
Same on my hand, the issue looks fixed! Thanks :-)

**Comment by nono** [comment] 2019-05-06 07:09
Yeah!

**Closed by nono** 2019-05-06 07:09 UTC
Labels: bug

**Comment by bristow** [comment] 2019-05-06 16:27
Same thing here, desktop doesn't freeze anymore.

But, during about 5 minutes, CPU is very in use.
Thanks !
