### ISSUE TITLE
TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by thblt** [cozy-labs/cozy-desktop#448] opened 2016-09-21 17:36 UTC
This is the second time I get this error, but I'm afraid this bug report may lack some details. 

This happens with `cozy-desktop sync` 

``` 
[2016-09-21 19:29:24:787] info - Local watcher  | File added Philo/Textes/Teller/A_Poor_Man's_Guide_to
_Surveniance_and_Determination.pdf
[2016-09-21 19:29:24:912] info - Remote writer  | Resolve a conflict: Concours/Cours/Esthétique/Paris1
0.org → Concours/Cours/Esthétique/Paris10-conflict-2016-09-21T17:29:24.911Z.org
/usr/lib/node_modules/cozy-desktop/lib/remote/index.js:483
      return this.couch.get(src.remote._id, (function(_this) {
                                      ^

TypeError: Cannot read property '_id' of undefined
    at Remote.resolveConflict (/usr/lib/node_modules/cozy-desktop/lib/remote/index.js:483:39)
    at Remote.resolveConflict (/usr/lib/node_modules/cozy-desktop/lib/remote/index.js:4:59)
    at Merge.resolveConflict (/usr/lib/node_modules/cozy-desktop/lib/merge.js:131:25)
    at /usr/lib/node_modules/cozy-desktop/lib/merge.js:206:28
    at /usr/lib/node_modules/cozy-desktop/lib/pouch.js:279:22
    at /usr/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:119:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

A bit of context:

 - The very fact that there's supposed to be a conflict is weird, since the file has just been created, and I'm not aware of any other computer syncing with my cozy (not a computer being used, anyway.  My home computer may be on, but nobody's using it.)
 - I had to run `cozy-desktop` manually because the instance I start with X has exited for some reason.  Its log ends with:

``` 
[2016-09-21 17:00:51:549] [34minfo[39m - Remote writer  | Overwrite file Concours/Cours/Esthétique/Paris10.org
[2016-09-21 17:00:51:600] [34minfo[39m - Remote writer  | Upload binary 90815a11925984381c29a81ce210b3c79426dff8

[2016-09-21 17:00:51:862] [34minfo[39m - Remote CouchDB | Binary uploaded
[2016-09-21 17:00:55:114] [34minfo[39m - Synchronize    | apply {"id":"Concours/Cours/Esthétique/Paris10.org","changes":[{"rev":"63-f1767dad5d1ecb4d63ff5beaa0c97e35"}],"doc":{"path":"Concours/Cours/Esthétique/Paris10.org","docType":"file","checksum":"90815a11925984381c29a81ce210b3c79426dff8","creationDate":"2016-09-21T14:05:12.009Z","lastModification":"2016-09-21T15:00:50.526Z","size":516,"class":"document","mime":"application/vnd.lotus-organizer","sides":{"local":62,"remote":61},"tags":[],"remote":{"_id":"836b0a30c8d44a279ca9618cbc9aead7","_rev":"13-a91ddf1513a9325748eea73a54e0eb30","binary":{"_id":"d3be9f1f4f839b191838e66f84a5d34ab3a80651","_rev":"1-87ce9bd8faa3966f719fa784d89e9f42"}},"errors":1,"_id":"Concours/Cours/Esthétique/Paris10.org","_rev":"63-f1767dad5d1ecb4d63ff5beaa0c97e35"},"seq":464}
[2016-09-21 17:00:55:118] [34minfo[39m - Remote writer  | Overwrite file Concours/Cours/Esthétique/Paris10.org
[2016-09-21 17:00:55:164] [34minfo[39m - Remote writer  | Upload binary 90815a11925984381c29a81ce210b3c79426dff8
[2016-09-21 17:00:58:317] [34minfo[39m - Synchronize    | apply {"id":"Concours/Cours/Esthétique/Paris10.org","changes":[{"rev":"64-2c5c888b559b9e766dc760d2e87aeb43"}],"doc":{"path":"Concours/Cours/Esthétique/Paris10.org","docType":"file","checksum":"90815a11925984381c29a81ce210b3c79426dff8","creationDate":"2016-09-21T14:05:12.009Z","lastModification":"2016-09-21T15:00:50.526Z","size":516,"class":"document","mime":"application/vnd.lotus-organizer","sides":{"local":62,"remote":61},"tags":[],"remote":{"_id":"836b0a30c8d44a279ca9618cbc9aead7","_rev":"13-a91ddf1513a9325748eea73a54e0eb30","binary":{"_id":"d3be9f1f4f839b191838e66f84a5d34ab3a80651","_rev":"1-87ce9bd8faa3966f719fa784d89e9f42"}},"errors":2,"_id":"Concours/Cours/Esthétique/Paris10.org","_rev":"64-2c5c888b559b9e766dc760d2e87aeb43"},"seq":465}
[2016-09-21 17:00:58:320] [34minfo[39m - Remote writer  | Overwrite file Concours/Cours/Esthétique/Paris10.org
[2016-09-21 17:00:58:360] [34minfo[39m - Remote writer  | Upload binary 90815a11925984381c29a81ce210b3c79426dff8
``` 

Of course, because I'm dumb, I wasn't redirecting stderr to a log file, which I'll do now, and report to you if anything there seems interesting.

**Comment by thblt** [comment] 2016-09-21 17:40
Hmm, I suspect I've just duplicated #355.  Should I close this?

**Comment by nono** [comment] 2016-09-21 18:21
Hi @thblt,

I don't think it's a duplicate of #355. The stack trace are not the same and it's not the same property that was missing.

Just to be sure, Paris10.org is a local file that you are editing with emacs (org mode) and you frequently saves it. I'm right? I can try to simulate a lot of writes to see if I can reproduce it.

**Comment by thblt** [comment] 2016-09-21 18:53
Thanks (as usual) for your quick reply.  

Yes, Paris10.org is an org-mode file, and I (very) frequently save file in Emacs (My Emacs is configured to save on losing focus, and I tend to it C-x s more often than necessary).  The version of this file in my Cozy is older version than the locally stored one, so it seems that cozy-desktop crashed while I was working on it.

For what it's worth:

 - By default, Emacs doesn't do anything when save is called on an unmodified buffer, *but* because it often considers the file to have been externally modified because of #446, it *may* sometimes write exactly the same contents to the file.
 - The version of Paris10.org in my Cozy doesn't seem truncated (saved/uploaded partially). I can't be sure, of course, but it looks like a normal state.  Sync was simply interrupted at some point.

**Comment by thblt** [comment] 2016-09-21 19:25
I'm back home: my other computer was off the whole day, and thus wasn't syncing.  The bug then occured with only one computer connected to the Cozy

**Comment by thblt** [comment] 2016-09-22 13:55
For what's it's worth, again:  renaming Paris10.org seems to have fixed the problem for now.

**Comment by nono** [comment] 2016-09-23 14:00
I think I may have found a path in the code that can lead to this error. I hope that #449 fixes your bug.

**Closed** 2016-10-05 07:29 UTC
Labels: bug

**Comment by thblt** [comment] 2016-10-07 20:16
Thanks!
