### ISSUE TITLE
Appimage for 3.37 fails to start on Linux (Debian 11)

### ISSUE THREAD

**Issue by cosminribo** [cozy-labs/cozy-desktop#2289] opened 2023-03-19 20:01 UTC
### Description

After upgrading Cozy Drive version 3.37 - it does no longer start. Previous version worked without issues.

### Steps to Reproduce

Launching from the terminal allows to see that the error comes from the installed version of glib.

### Expected behavior

The application to start.

[What actually happened]

$ ./Cozy-Drive-3.37.0-x86_64.AppImage 

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Cozy-DefGU2m/resources/app.asar.unpacked/node_modules/@parcel/watcher/build/Release/watcher.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at load (/tmp/.mount_Cozy-DefGU2m/resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/tmp/.mount_Cozy-DefGU2m/resources/app.asar/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)

### Informations

The bug is reproducible - and there is no easy way to update glib. Version 2.31 is still in use in many Debian based distributions.
OS: MxLinux
System: Kernel: 5.10.0-21-amd64 [5.10.162-1] x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.10.0-21-amd64 
           Desktop: Xfce 4.18.1 tk: Gtk 3.24.24 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 
           dm: LightDM 1.26.0 Distro: MX-21.3_x64 Wildflower October 20  2021 
           base: Debian GNU/Linux 11 (bullseye) 
Version 3.37

**Comment by Crash--** [comment] 2023-03-20 07:26
Thanks for opening the issue, very appreciated. 

This issue is a duplicate of https://github.com/cozy-labs/cozy-desktop/issues/2283 . We're working on a fix, currently in beta. Will publish a 3.38 ASAP. 

I'm closing this issue to keep only one for this bug.

**Closed by Crash--** 2023-03-20 07:26 UTC

**Comment by cosminribo** [comment] 2023-03-20 09:51
Thank you. Good to know you could find a solution!
